In [1]:
# Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Miscellaneous Settings
pd.options.mode.chained_assignment = None  # default='warn'

In [2]:
dataset = "https://github.com/xyjiang970/cis9655-data-visualization/blob/main/project/Datasets/UN_DESA_migration.csv?raw=true"
migration_data = pd.read_csv(dataset)

In [3]:
migration_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16561 entries, 0 to 16560
Data columns (total 43 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Year                                            16561 non-null  int64
 1   Country                                         16561 non-null  object
 2   Resettled by destination per capita             529 non-null    float64
 3   Remittances (% GDP)                             7389 non-null   float64
 4   Five-year change immigrants                     5517 non-null   float64
 5   Refugees by destination                         5405 non-null   float64
 6   Child migrants (UNICEF)                         244 non-null    float64
 7   Resettled by origin                             2613 non-null   float64
 8   Child migrants (under-20s)                      5995 non-null   float64
 9   Asylum seekers by origin (per capita)           3086 non-null   float64
 10  Child migrants per capita (under-20s)           1440 non-null   float64
 11  Five-year change immigrants per capita          1216 non-null   float64
 12  Refugees by destination.1                       6212 non-null   float64
 13  Resettled by destination                        529 non-null    float64
 14  Internal displacement (disasters)               190 non-null    float64
 15  Annual internal displacements (Disaster)        818 non-null    float64
 16  Asylum seekers by destination                   2504 non-null   float64
 17  Five-year change emigrants                      5556 non-null   float64
 18  Annual internal displacement from conflict (%)  314 non-null    float64
 19  Refugees by destination (per capita)            1058 non-null   float64
 20  Refugees by origin (per capita)                 5598 non-null   float64
 21  Child migrants (UNICEF, under-18s)              193 non-null    float64
 22  Refugees by origin                              5884 non-null   float64
 23  Internal displacement (disaster)                198 non-null    float64
 24  Emigrants                                       6002 non-null   float64
 25  Annual internal displacement (conflict)         319 non-null    float64
 26  Internal displacement share (conflict)          359 non-null    float64
 27  Asylum seekers by origin                        3183 non-null   float64
 28  International immigrants (% population)         1425 non-null   float64
 29  International migrants                          5959 non-null   float64
 30  Internal displacement (conflict)                372 non-null    float64
 31  Asylum seekers by destination (per capita)      2459 non-null   float64
 32  Resettled arrivals by origin (per capita)       2465 non-null   float64
 33  Annual internal displacement from disaster (%)  810 non-null    float64
 34  Net migration rate                              6770 non-null   float64
 35  Remittances cost (to)                           540 non-null    float64
 36  Child migrants (UNDESA)                         5995 non-null   float64
 37  Child migrants per capita (UNDESA)              1440 non-null   float64
 38  Net migration                                   6770 non-null   float64
 39  Remittances cost (from)                         203 non-null    float64
 40  Five-year change emigrants per capita           1230 non-null   float64
 41  International emigrants (% population)          1440 non-null   float64
 42  Refugees by destination (per capita).1          6072 non-null   float64
dtypes: float64(41), int64(1), object(1)
memory usage: 5.4+ MB

In [4]:
migration_data = migration_data.groupby("Year")

In [5]:
migration_data.head(5)

,Year,Country,Resettled by destination per capita,Remittances (% GDP),Five-year change immigrants,Refugees by destination,Child migrants (UNICEF),Resettled by origin,Child migrants (under-20s),Asylum seekers by origin (per capita),...,Annual internal displacement from disaster (%),Net migration rate,Remittances cost (to),Child migrants (UNDESA),Child migrants per capita (UNDESA),Net migration,Remittances cost (from),Five-year change emigrants per capita,International emigrants (% population),Refugees by destination (per capita).1
0,1955,Central and Southern Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.197,NaN,NaN,NaN,525786.0,NaN,NaN,NaN,NaN
1,1960,Central and Southern Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.275,NaN,NaN,NaN,809851.0,NaN,NaN,NaN,NaN
2,1965,Central and Southern Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.176,NaN,NaN,NaN,577018.0,NaN,NaN,NaN,NaN
3,1970,Central and Southern Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.022,NaN,NaN,NaN,82258.0,NaN,NaN,NaN,NaN
4,1975,Central and Southern Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-0.285,NaN,NaN,NaN,-1174222.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4773,1954,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.074
4775,1956,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.954
4776,1957,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.442
4777,1958,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.914
4778,1959,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.342

In [6]:
migration_data.to_csv('result.csv', index=False)

AttributeError: 'DataFrameGroupBy' object has no attribute 'to_csv'